# Style setting
set -g default-terminal "tmux-256color"
# set -g status-style bg=default,fg=white
# set -g pane-border-style fg='#888888'
# set -g pane-active-border-style fg='#888888'
# set -g status-position bottom

# Tmux passthrough for jupyter rendering image/gif
set -g allow-passthrough on

# Key binding
## Prefix binding
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

## Pane splitting binding
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Reload tmux config
unbind r
bind r source-file ~/.tmux.conf

# Vim binding
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Resize and maxi-minimize pane
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
bind M-c attach-session -c "#{pane_current_path}"
set -g mouse on

# remove delay for exiting insert mode with esc in nvim
set -sg escape-time 10

# Enter copy mode for terminal
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
unbind -T copy-mode-vi MouseDragEnd1Pane

# Plugins installation
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# set theme
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"

# make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

run '~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux'
run '~/.tmux/plugins/tpm/tpm'
